name: Actions Workflow

#   on: [push, pull_request,pull ]
#   on: 
#     push:
#     pull_request:
#       types: [closed, assigned, opened, reopened]

on: 
   # push:
   pull_request:   
      # branches-ignore: # ignoring branches
      branches:
         - master
         - 'feature/*' # matches feature/featA, feature/featB  and doesn't math feature/feat/a
         - 'feature/**' # will match all variants
         - '!feature/featC' # this '!' sign meant ignore particular branchv
      # tags:
      #    - v1.*
      # tags-ignore:      
      paths:
         - '**.js' 
         - '!filename.js'
      # paths-ignore: # can't be used at the same time
      #    - 'docs/**'

   # repository_dispatch: # for manual trigger
   #    types: [build]

   # schedule:
   #  - cron: "0/5 * * * *"
   #  - cron: "0/6 * * * *"
   pull_request:
      types: [closed, assigned, opened, reopened]

jobs:
   run-github-actions:
      runs-on: ubuntu-latest
      steps:
         -  name: payloads
            run: echo ${{github.event.client_payload.env}}
         -  name: List Files
            run: |
               pwd
               ls -a
               echo $GITHUB_SHA
               echo $GITHUB_REPOSITORY
               echo $GITHB_WORKSPACE
               echo "${{ github.token}}"
               # git clone git@github:$GITHUB_REPOSITORY
               # git checkout echo $GITHUB_SHA
         -  name: Chewckout
            uses: actions/checkout@v1
         -  name: List Files
            run: |
               pwd
               ls -a   
         -  name: Simple JS Action
            id: greet # Id of the step
            uses: actions/hello-world-javascript-action@v1
            #    uses: actions/hello-world-javascript-action@master
            with:
               who-to-greet: John
         -  name: Log Greeting Time
            run: echo "${{steps.greet.outputs.time}}" # here we get na access to the list of steps