
  name: Actions Workflow

  on: [push]

  jobs:
    run-github-actions:
        runs-on: ubuntu-latest
        steps:
            -  name: List Files
               run: |
                  pwd
                  ls -a
            -  name: Chewckout
               uses: actions/checkout@v1
            -  name: List Files
               run: |
                  pwd
                  ls -a   
            -  name: Simple JS Action
               id: greet # Id of the step
               uses: actions/hello-world-javascript-action@v1
            #    uses: actions/hello-world-javascript-action@master
               with:
                 who-to-greet: John
            -  name: Log Greeting Time
               run: echo "${{steps.greet.outputs.time}}" # here we get na access to the list of steps