name: Actions Workflow

on: [push]

jobs:
    run-github-actions:
        runs-on: windows-latest
        steps:
            -  name: Simple JS Action
               id: greet
               uses: actions/hello-world-javascript-action@v1
            #    uses: actions/hello-world-javascript-action@master
               with:
                  who-to-greet: John
            -  name: Log Greeting Time
               run: echo "${{steps.greet.outputs}}"